
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgukkzjwudbxyiohspsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndWtremp3dWRieHlpb2hzcHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjE2NTAsImV4cCI6MjA2NDEzNzY1MH0.o7NqJ5pNNhDEuk5l58k_Wivn2qrszNOan1PNcFLVW78";

// Configuración mejorada para mejor persistencia de sesiones
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: 'corilog-auth',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Configuración específica para manejo de tokens
    debug: process.env.NODE_ENV === 'development',
  },
  global: {
    headers: {
      'x-application-name': 'corilog'
    }
  }
});

// Configurar logging de eventos de autenticación para debugging
if (process.env.NODE_ENV === 'development') {
  supabase.auth.onAuthStateChange((event, session) => {
    console.log('🔐 Auth State Change:', {
      event,
      hasSession: !!session,
      userId: session?.user?.id,
      expiresAt: session?.expires_at ? new Date(session.expires_at * 1000) : null,
      timestamp: new Date().toISOString()
    });
  });
}
