// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgukkzjwudbxyiohspsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndWtremp3dWRieHlpb2hzcHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjE2NTAsImV4cCI6MjA2NDEzNzY1MH0.o7NqJ5pNNhDEuk5l58k_Wivn2qrszNOan1PNcFLVW78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);